from __future__ import annotations

from enum import StrEnum


class ExecutionStatus(StrEnum):
    ADMISSION_DENIED = "ADMISSION_DENIED"
    INVALID_EXECUTION_CONFIG = "INVALID_EXECUTION_CONFIG"
    TASK_PACKET_TOO_LARGE = "TASK_PACKET_TOO_LARGE"
    SPAWN_FAILED = "SPAWN_FAILED"
    SPAWN_FAILED_AFTER_ADMISSION = "SPAWN_FAILED_AFTER_ADMISSION"
    TIMEOUT = "TIMEOUT"
    INTERRUPTED = "INTERRUPTED"
    USAGE_MISSING = "USAGE_MISSING"
    USAGE_MALFORMED = "USAGE_MALFORMED"
    USAGE_BUDGET_EXCEEDED = "USAGE_BUDGET_EXCEEDED"
    PROCESS_FAILED = "PROCESS_FAILED"
    COMPLETED = "COMPLETED"
    CONTROL_PLANE_UNAVAILABLE = "CONTROL_PLANE_UNAVAILABLE"
    CONTROL_PLANE_PROTOCOL_ERROR = "CONTROL_PLANE_PROTOCOL_ERROR"
    CONTROL_PLANE_UNAUTHORIZED = "CONTROL_PLANE_UNAUTHORIZED"
    PROVIDER_AUTH_BLOCKED = "PROVIDER_AUTH_BLOCKED"
    PROVIDER_QUOTA_PAUSED = "PROVIDER_QUOTA_PAUSED"
    PROVIDER_UNKNOWN = "PROVIDER_UNKNOWN"
    MODEL_CALL_BUDGET_BLOCKED = "MODEL_CALL_BUDGET_BLOCKED"
    CHECKPOINT_REQUIRED = "CHECKPOINT_REQUIRED"
    STOP_AND_CHECKPOINT = "STOP_AND_CHECKPOINT"


class UsageStatus(StrEnum):
    NOT_RUN = "NOT_RUN"
    VALID = "VALID"
    MISSING = "MISSING"
    MALFORMED = "MALFORMED"


class UsageError(ValueError):
    """Raised when bounded Hermes usage evidence is invalid."""
