BEGIN EXCLUSIVE;
CREATE TABLE schema_migrations (migration_id TEXT PRIMARY KEY, checksum_sha256 TEXT NOT NULL UNIQUE CHECK(length(checksum_sha256)=64 AND checksum_sha256=lower(checksum_sha256)), applied_at TEXT NOT NULL CHECK(substr(applied_at,-1)='Z'), service_version TEXT NOT NULL, description TEXT NOT NULL) STRICT;
CREATE TABLE registry_metadata (metadata_key TEXT PRIMARY KEY, metadata_value TEXT NOT NULL, updated_at TEXT NOT NULL CHECK(substr(updated_at,-1)='Z')) STRICT;
CREATE TABLE tasks (
 task_id TEXT PRIMARY KEY CHECK(length(task_id)=41 AND substr(task_id,1,5)='task_' AND task_id=lower(task_id)), schema_version TEXT NOT NULL, created_at TEXT NOT NULL CHECK(substr(created_at,-1)='Z'), created_by TEXT NOT NULL CHECK(json_valid(created_by) AND json_type(created_by)='object'), requested_by TEXT NOT NULL CHECK(json_valid(requested_by) AND json_type(requested_by)='object'), state TEXT NOT NULL CHECK(state IN ('CREATED','READY','RUNNING','PAUSED','BLOCKED','VALIDATING','REVIEW','TERMINAL')), risk_class TEXT NOT NULL CHECK(risk_class IN ('GREEN','YELLOW','RED','UNKNOWN')), task_contract_ref TEXT, allowed_operations TEXT NOT NULL CHECK(json_valid(allowed_operations) AND json_type(allowed_operations)='array'), resource_budget TEXT NOT NULL CHECK(json_valid(resource_budget) AND json_type(resource_budget)='object'), prerequisite_status TEXT NOT NULL CHECK(json_valid(prerequisite_status) AND json_type(prerequisite_status)='object'), pause_reason TEXT CHECK(pause_reason IS NULL OR (json_valid(pause_reason) AND json_type(pause_reason)='object')), terminal_result TEXT CHECK(terminal_result IS NULL OR (json_valid(terminal_result) AND json_type(terminal_result)='object')), current_checkpoint_id TEXT CHECK(current_checkpoint_id IS NULL OR (length(current_checkpoint_id)=40 AND substr(current_checkpoint_id,1,4)='chk_' AND current_checkpoint_id=lower(current_checkpoint_id))), revision INTEGER NOT NULL DEFAULT 0 CHECK(revision>=0), last_event_sequence INTEGER NOT NULL DEFAULT 0 CHECK(last_event_sequence>=0), CHECK((state='PAUSED')=(pause_reason IS NOT NULL)), CHECK((state='TERMINAL')=(terminal_result IS NOT NULL))
) STRICT;
CREATE TABLE resource_leases (
 resource_id TEXT PRIMARY KEY CHECK(length(resource_id)=41 AND substr(resource_id,1,5)='rsrc_' AND resource_id=lower(resource_id)), task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE RESTRICT, schema_version TEXT NOT NULL, resource_type TEXT NOT NULL CHECK(resource_type IN ('WORKER','PROCESS','PREVIEW','WORKTREE','TEMP_DIR','TEST_ENV','ARTIFACT','DELEGATED_RUN')), created_at TEXT NOT NULL CHECK(substr(created_at,-1)='Z'), created_by TEXT NOT NULL CHECK(json_valid(created_by) AND json_type(created_by)='object'), state TEXT NOT NULL CHECK(state IN ('ALLOCATED','ACTIVE','IDLE','TERMINAL','HEARTBEAT_MISSED','STALE_CANDIDATE')), requested_operation TEXT NOT NULL CHECK(json_valid(requested_operation) AND json_type(requested_operation)='object'), budget_reservation TEXT NOT NULL CHECK(json_valid(budget_reservation) AND json_type(budget_reservation)='object'), expected_identity TEXT NOT NULL CHECK(json_valid(expected_identity) AND json_type(expected_identity)='object'), bound_identity TEXT CHECK(bound_identity IS NULL OR (json_valid(bound_identity) AND json_type(bound_identity)='object')), heartbeat_required INTEGER NOT NULL CHECK(heartbeat_required IN (0,1)), last_heartbeat TEXT CHECK(last_heartbeat IS NULL OR substr(last_heartbeat,-1)='Z'), ttl_seconds INTEGER CHECK(ttl_seconds IS NULL OR ttl_seconds>0), cleanup_policy TEXT NOT NULL CHECK(json_valid(cleanup_policy) AND json_type(cleanup_policy)='object'), cleanup_authority TEXT NOT NULL CHECK(json_valid(cleanup_authority) AND json_type(cleanup_authority)='object'), metadata TEXT NOT NULL CHECK(json_valid(metadata) AND json_type(metadata)='object'), terminal_reason TEXT CHECK(terminal_reason IS NULL OR json_valid(terminal_reason)), revision INTEGER NOT NULL DEFAULT 0 CHECK(revision>=0), last_event_sequence INTEGER NOT NULL DEFAULT 0 CHECK(last_event_sequence>=0), CHECK(state!='ACTIVE' OR bound_identity IS NOT NULL), CHECK(heartbeat_required=1 OR last_heartbeat IS NULL), CHECK((state='TERMINAL')=(terminal_reason IS NOT NULL))
) STRICT;
CREATE TABLE audit_events (
 event_id TEXT PRIMARY KEY CHECK(length(event_id)=40 AND substr(event_id,1,4)='evt_' AND event_id=lower(event_id)), sequence INTEGER NOT NULL UNIQUE CHECK(sequence>0), schema_version TEXT NOT NULL, event_type TEXT NOT NULL, occurred_at TEXT NOT NULL CHECK(substr(occurred_at,-1)='Z'), task_id TEXT REFERENCES tasks(task_id) ON DELETE RESTRICT, resource_id TEXT REFERENCES resource_leases(resource_id) ON DELETE RESTRICT, actor TEXT NOT NULL CHECK(json_valid(actor) AND json_type(actor)='object'), correlation_id TEXT NOT NULL CHECK(length(correlation_id)=41 AND substr(correlation_id,1,5)='corr_' AND correlation_id=lower(correlation_id)), payload TEXT NOT NULL CHECK(json_valid(payload) AND json_type(payload)='object'), prior_event_hash TEXT CHECK(prior_event_hash IS NULL OR (length(prior_event_hash)=64 AND prior_event_hash=lower(prior_event_hash))), event_hash TEXT NOT NULL CHECK(length(event_hash)=64 AND event_hash=lower(event_hash)), CHECK((sequence=1 AND prior_event_hash IS NULL) OR (sequence>1 AND prior_event_hash IS NOT NULL))
) STRICT;
CREATE TABLE heartbeats (
 heartbeat_scope TEXT PRIMARY KEY, schema_version TEXT NOT NULL, task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE RESTRICT, resource_id TEXT REFERENCES resource_leases(resource_id) ON DELETE RESTRICT, producer TEXT NOT NULL CHECK(json_valid(producer) AND json_type(producer)='object'), sequence INTEGER NOT NULL CHECK(sequence>=0), producer_monotonic_ns INTEGER CHECK(producer_monotonic_ns IS NULL OR producer_monotonic_ns>=0), observed_at TEXT NOT NULL CHECK(substr(observed_at,-1)='Z'), received_at TEXT NOT NULL CHECK(substr(received_at,-1)='Z'), status TEXT NOT NULL CHECK(status IN ('EXPECTED','PAUSED','COMPLETING','FAILED','UNKNOWN')), evidence_ref TEXT, last_event_id TEXT NOT NULL UNIQUE REFERENCES audit_events(event_id) ON DELETE RESTRICT, CHECK((resource_id IS NULL AND heartbeat_scope='task:' || task_id) OR (resource_id IS NOT NULL AND heartbeat_scope='resource:' || resource_id))
) STRICT;
CREATE TABLE gates (
 gate_id TEXT PRIMARY KEY CHECK(length(gate_id)=41 AND substr(gate_id,1,5)='gate_' AND gate_id=lower(gate_id)), schema_version TEXT NOT NULL, task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE RESTRICT, resource_id TEXT REFERENCES resource_leases(resource_id) ON DELETE RESTRICT, requested_operation TEXT NOT NULL CHECK(json_valid(requested_operation) AND json_type(requested_operation)='object'), risk_class TEXT NOT NULL CHECK(risk_class IN ('GREEN','YELLOW','RED','UNKNOWN')), requested_at TEXT NOT NULL CHECK(substr(requested_at,-1)='Z'), requested_by TEXT NOT NULL CHECK(json_valid(requested_by) AND json_type(requested_by)='object'), required_authority TEXT NOT NULL CHECK(json_valid(required_authority) AND json_type(required_authority)='object'), status TEXT NOT NULL CHECK(status IN ('PENDING','APPROVED','DENIED','EXPIRED','CONSUMED')), approved_by TEXT CHECK(approved_by IS NULL OR (json_valid(approved_by) AND json_type(approved_by)='object')), approved_at TEXT CHECK(approved_at IS NULL OR substr(approved_at,-1)='Z'), expires_at TEXT CHECK(expires_at IS NULL OR substr(expires_at,-1)='Z'), authorization_reference TEXT, consumed_at TEXT CHECK(consumed_at IS NULL OR substr(consumed_at,-1)='Z'), revision INTEGER NOT NULL DEFAULT 0 CHECK(revision>=0), last_event_sequence INTEGER NOT NULL DEFAULT 0 CHECK(last_event_sequence>=0), CHECK((status IN ('APPROVED','CONSUMED') AND approved_by IS NOT NULL AND approved_at IS NOT NULL AND expires_at IS NOT NULL AND authorization_reference IS NOT NULL) OR status NOT IN ('APPROVED','CONSUMED')), CHECK((status='CONSUMED')=(consumed_at IS NOT NULL))
) STRICT;
CREATE TABLE checkpoints (
 checkpoint_id TEXT PRIMARY KEY CHECK(length(checkpoint_id)=40 AND substr(checkpoint_id,1,4)='chk_' AND checkpoint_id=lower(checkpoint_id)), task_id TEXT NOT NULL REFERENCES tasks(task_id) ON DELETE RESTRICT, schema_version TEXT NOT NULL, created_at TEXT NOT NULL CHECK(substr(created_at,-1)='Z'), created_by TEXT NOT NULL CHECK(json_valid(created_by) AND json_type(created_by)='object'), task_state TEXT NOT NULL CHECK(task_state IN ('CREATED','READY','RUNNING','PAUSED','BLOCKED','VALIDATING','REVIEW','TERMINAL')), branch TEXT, worktree TEXT, head_sha TEXT, active_resource_ids TEXT NOT NULL CHECK(json_valid(active_resource_ids) AND json_type(active_resource_ids)='array'), pending_validation TEXT NOT NULL CHECK(json_valid(pending_validation) AND json_type(pending_validation)='array'), next_permitted_action TEXT CHECK(next_permitted_action IS NULL OR (json_valid(next_permitted_action) AND json_type(next_permitted_action)='object')), blocking_reason TEXT CHECK(blocking_reason IS NULL OR (json_valid(blocking_reason) AND json_type(blocking_reason)='object')), provider_state TEXT CHECK(provider_state IS NULL OR (json_valid(provider_state) AND json_type(provider_state)='object')), evidence_refs TEXT NOT NULL CHECK(json_valid(evidence_refs) AND json_type(evidence_refs)='array')
) STRICT;
CREATE TABLE idempotency_requests (
 caller_id TEXT NOT NULL, idempotency_key TEXT NOT NULL, operation TEXT NOT NULL, request_fingerprint TEXT NOT NULL CHECK(length(request_fingerprint)=64 AND request_fingerprint=lower(request_fingerprint)), created_at TEXT NOT NULL CHECK(substr(created_at,-1)='Z'), finalized_at TEXT, status TEXT NOT NULL CHECK(status IN ('IN_PROGRESS','SUCCEEDED','FAILED')), result_reference TEXT, response_code TEXT, response_body TEXT CHECK(response_body IS NULL OR json_valid(response_body)), PRIMARY KEY(caller_id,idempotency_key)
) STRICT;
CREATE INDEX tasks_state_created_idx ON tasks(state,created_at);
CREATE INDEX resource_task_state_idx ON resource_leases(task_id,state,resource_type);
CREATE UNIQUE INDEX active_bound_identity_idx ON resource_leases(resource_type,bound_identity) WHERE bound_identity IS NOT NULL AND state IN ('ACTIVE','IDLE','HEARTBEAT_MISSED','STALE_CANDIDATE');
CREATE UNIQUE INDEX active_preview_endpoint_idx ON resource_leases(json_extract(metadata,'$.bind_address'),json_extract(metadata,'$.port')) WHERE resource_type='PREVIEW' AND state IN ('ALLOCATED','ACTIVE','IDLE','HEARTBEAT_MISSED','STALE_CANDIDATE');
CREATE UNIQUE INDEX active_worktree_path_idx ON resource_leases(json_extract(metadata,'$.path')) WHERE resource_type='WORKTREE' AND state IN ('ALLOCATED','ACTIVE','IDLE','HEARTBEAT_MISSED','STALE_CANDIDATE');
CREATE INDEX audit_task_sequence_idx ON audit_events(task_id,sequence);
CREATE INDEX audit_resource_sequence_idx ON audit_events(resource_id,sequence);
CREATE INDEX gates_pending_expiry_idx ON gates(status,expires_at,requested_at);
CREATE INDEX checkpoints_task_created_idx ON checkpoints(task_id,created_at DESC);
CREATE TRIGGER audit_events_no_update BEFORE UPDATE ON audit_events BEGIN SELECT RAISE(ABORT,'AUDIT_APPEND_ONLY'); END;
CREATE TRIGGER audit_events_no_delete BEFORE DELETE ON audit_events BEGIN SELECT RAISE(ABORT,'AUDIT_APPEND_ONLY'); END;
CREATE TRIGGER checkpoints_no_update BEFORE UPDATE ON checkpoints BEGIN SELECT RAISE(ABORT,'CHECKPOINT_IMMUTABLE'); END;
CREATE TRIGGER checkpoints_no_delete BEFORE DELETE ON checkpoints BEGIN SELECT RAISE(ABORT,'CHECKPOINT_IMMUTABLE'); END;
CREATE TRIGGER tasks_no_delete BEFORE DELETE ON tasks BEGIN SELECT RAISE(ABORT,'TASK_RETAINED'); END;
CREATE TRIGGER resource_leases_no_delete BEFORE DELETE ON resource_leases BEGIN SELECT RAISE(ABORT,'RESOURCE_LEASE_RETAINED'); END;
CREATE TRIGGER gates_no_delete BEFORE DELETE ON gates BEGIN SELECT RAISE(ABORT,'GATE_RETAINED'); END;
CREATE TRIGGER tasks_update_guard BEFORE UPDATE ON tasks BEGIN
 SELECT CASE WHEN NEW.task_id<>OLD.task_id OR NEW.schema_version<>OLD.schema_version OR NEW.created_at<>OLD.created_at OR NEW.created_by<>OLD.created_by OR NEW.requested_by<>OLD.requested_by OR NEW.risk_class<>OLD.risk_class OR NEW.task_contract_ref IS NOT OLD.task_contract_ref OR NEW.allowed_operations<>OLD.allowed_operations OR NEW.resource_budget<>OLD.resource_budget OR NEW.prerequisite_status<>OLD.prerequisite_status THEN RAISE(ABORT,'TASK_IMMUTABLE_FIELD') END;
 SELECT CASE WHEN OLD.state='TERMINAL' THEN RAISE(ABORT,'TASK_TERMINAL_IMMUTABLE') END;
 SELECT CASE WHEN NOT ((NEW.revision=OLD.revision+1) OR (NEW.revision=OLD.revision AND NEW.state=OLD.state AND NEW.pause_reason IS OLD.pause_reason AND NEW.terminal_result IS OLD.terminal_result AND NEW.current_checkpoint_id IS OLD.current_checkpoint_id AND NEW.last_event_sequence>=OLD.last_event_sequence)) THEN RAISE(ABORT,'TASK_REVISION_CONFLICT') END;
END;
CREATE TRIGGER resource_leases_update_guard BEFORE UPDATE ON resource_leases BEGIN
 SELECT CASE WHEN OLD.state='TERMINAL' THEN RAISE(ABORT,'RESOURCE_TERMINAL_IMMUTABLE') END;
 SELECT CASE WHEN OLD.bound_identity IS NOT NULL AND NEW.bound_identity IS NOT OLD.bound_identity THEN RAISE(ABORT,'RESOURCE_IDENTITY_IMMUTABLE') END;
 SELECT CASE WHEN NOT ((NEW.revision=OLD.revision+1) OR (NEW.revision=OLD.revision AND NEW.state=OLD.state AND NEW.bound_identity IS OLD.bound_identity AND NEW.last_event_sequence>=OLD.last_event_sequence)) THEN RAISE(ABORT,'RESOURCE_REVISION_CONFLICT') END;
END;
CREATE TRIGGER gates_update_guard BEFORE UPDATE ON gates BEGIN
 SELECT CASE WHEN OLD.status IN ('DENIED','EXPIRED','CONSUMED') THEN RAISE(ABORT,'GATE_IMMUTABLE') END;
 SELECT CASE WHEN NOT ((NEW.revision=OLD.revision+1) OR (NEW.revision=OLD.revision AND NEW.status=OLD.status AND NEW.last_event_sequence>=OLD.last_event_sequence)) THEN RAISE(ABORT,'GATE_REVISION_CONFLICT') END;
END;
COMMIT;
